parameters:
#    conf_inpt.example.class: Conf\InptBundle\Example

services:
#    conf_inpt.example:
#        class: %conf_inpt.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
