parameters:
#    conf_prof.example.class: Conf\ProfBundle\Example

services:
#    conf_prof.example:
#        class: %conf_prof.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
