security:
    encoders:
         FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ETUDIANT: ROLE_USER
        ROLE_PROF: ROLE_USER
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_PROF, ROLE_ETUDIANT]


    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/group, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/etudiant, role: ROLE_ETUDIANT }
        - { path: ^/professeur, role: ROLE_PROF }
        - { path: ^/administration, role: ROLE_ADMIN }
        - { path: ^/backoffice, role: ROLE_SUPER_ADMIN }