parameters:
#    conf_user.example.class: Conf\UserBundle\Example

services:
#    conf_user.example:
#        class: %conf_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
