parameters:
#    conf_etudiant.example.class: Conf\EtudiantBundle\Example

services:
#    conf_etudiant.example:
#        class: %conf_etudiant.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
